name: wilddex
description: "A PokÃ©dex for Animals!"


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  path_provider: ^2.1.5
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.2.2
  camera: ^0.10.0
  path: ^1.8.0
  http: ^1.2.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  isar_generator: ^3.1.0+1


flutter:
  uses-material-design: true

  assets:
    - assets/data/

  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2-Regular.ttf
        - asset: assets/fonts/Baloo2-Bold.ttf
          weight: 700
